version: '3.8'
services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe_listener
    command: listen --forward-to http://host.docker.internal:8081/api/stripe/webhook
    env_file:
      - ../../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
